export const COLORS = {
  BACKGROUND_PRIMARY: '#FFFFFF',
  BACKGROUND_PRIMARY_ACTIVE: '#FFDECC',
  BACKGROUND_SECONDARY: '#383838',
  BACKGROUND_SECONDARY_ACTIVE: '#D7D7D7',
  BACKGROUND_MODAL: 'rgba(56, 56, 56, 0.6)',
  DELIMITER: '#D7D7D7',
  FOREGROUND_PRIMARY: '#383838',
  FOREGROUND_PRIMARY_ACTIVE: '#FF5C00',
  FOREGROUND_PRIMARY_SUBTLE: '#888888',
  FOREGROUND_PRIMARY_DISABLED: '#CCCCCC',
  FOREGROUND_SECONDARY: '#FFFFFF',
  FOREGROUND_SECONDARY_ACTIVE: '#FFE5D6',
  SHADOW: '#D6D6D6',
  SHADOW_ACTIVE: '#FFA775',
  STATUS_BAR_BACKGROUND_COLOR: '#333333',
  STATUS_BAR_FOREGROUND_COLOR: '#FFFFFF'
};