export const COLORS = {
  BACKGROUND_PRIMARY: '#FFFFFF',
  BACKGROUND_PRIMARY_ACTIVE: '#FFDECC',
  BACKGROUND_SECONDARY: '#383838',
  BACKGROUND_SECONDARY_ACTIVE: '#D7D7D7',
  DELIMITER: '#D7D7D7',
  FOREGROUND_PRIMARY: '#383838',
  FOREGROUND_PRIMARY_ACTIVE: '#FF5C00',
  FOREGROUND_PRIMARY_SUBTLE: '#888888',
  FOREGROUND_SECONDARY: '#FFFFFF',
  SHADOW: '#D6D6D6',
  STATUS_BAR_BACKGROUND_COLOR: '#333333',
  STATUS_BAR_FOREGROUND_COLOR: '#FFFFFF'
};