export const COLORS = {
  STATUS_BAR_BACKGROUND_COLOR: '#383838',
  STATUS_BAR_FOREGROUND_COLOR: '#FFFFFF',
  PROMOTION_LISTING_BACKGROUND: '#383838',
  PROMOTION_LISTING_FOREGROUND: '#FFFFFF',
  CATEGORY_ITEM_TEXT_FOREGROUND: '#383838',
  CATEGORY_ITEM_TEXT_FOREGROUND_ACTIVE: '#383838',
  CATEGORY_ITEM_ICON_FOREGROUND: '#383838',
  CATEGORY_ITEM_ICON_FOREGROUND_ACTIVE: '#FF5C00',
  NAV_BUTTON_BACKGROUND: '#FFFFFF',
  NAV_BUTTON_BACKGROUND_ACTIVE: '#FFDECC',
  NAV_BUTTON_FOREGROUND: '#383838',
  NAV_BUTTON_FOREGROUND_ACTIVE: '#FF5C00'
};

export const CONTAINER_PADDING = 16;