export const ACTIONS = {
  SET_MODE: 'SET_MODE'
}

export const MODES = {
  CATALOG: 'CATALOG',
  CONTACTS: 'CONTACTS',
  PERSONAL_OFFICE: 'PERSONAL_OFFICE',
  PRODUCT_CART: 'PRODUCT_CART'
}

export const COLORS = {
  NAV_BUTTON_BACKGROUND: '#FFFFFF',
  NAV_BUTTON_BACKGROUND_ACTIVE: '#FFDECC',
  NAV_BUTTON_FOREGROUND: '#383838',
  NAV_BUTTON_FOREGROUND_ACTIVE: '#FF5C00'
}